version: '2.3'
services:
  facedetect:
    image: fdetect
    ports:
      - "5001:5000"
    volumes:
      #the following bind mount allows code changes to become live upon save
      - $COMPOSEDIR/src:/root/src
      #the following bind mount allows output files to persist on host
      - $COMPOSEDIR/output:/root/output
     #the following bind mount allows the camera to be visible to container
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    environment:
      - DISPLAY=unix$DISPLAY
    entrypoint: 
      - python
      - '-B'
      - /root/src/server.py
